from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from app.api import deps
from app.models.user import User
from app.models.resume import Resume
from app.rag.engine import get_vectorstore
from app.core.config import settings
from sqlalchemy.orm import Session
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate

router = APIRouter()

class JobMatchRequest(BaseModel):
    job_description: str
    resume_id: int

@router.get("/{resume_id}/parse")
async def get_parsed_resume(
    resume_id: int,
    db: Session = Depends(deps.get_db),
    current_user: User = Depends(deps.get_current_user),
):
    resume = db.query(Resume).filter(Resume.id == resume_id, Resume.owner_id == current_user.id).first()
    if not resume:
        raise HTTPException(status_code=404, detail="Resume not found")
        
    llm = ChatOpenAI(
        api_key=settings.OPENROUTER_API_KEY, 
        base_url="https://openrouter.ai/api/v1",
        model="nvidia/nemotron-3-ultra-550b-a55b:free"
    )
    prompt = PromptTemplate.from_template(
        "You are an expert resume parser. Extract the following from the resume text: Experience, Projects, Education, Skills, Certifications, Achievements, Links, Emails, Phone. Structure it in a neat JSON format.\n\nResume Text:\n{text}"
    )
    
    chain = prompt | llm
    response = chain.invoke({"text": resume.parsed_text[:3000]})
    
    return {"parsed_data": response.content}

@router.get("/{resume_id}/score")
async def get_resume_score(
    resume_id: int,
    db: Session = Depends(deps.get_db),
    current_user: User = Depends(deps.get_current_user),
):
    resume = db.query(Resume).filter(Resume.id == resume_id, Resume.owner_id == current_user.id).first()
    if not resume:
        raise HTTPException(status_code=404, detail="Resume not found")
        
    llm = ChatOpenAI(
        api_key=settings.OPENROUTER_API_KEY, 
        base_url="https://openrouter.ai/api/v1",
        model="nvidia/nemotron-3-ultra-550b-a55b:free"
    )
    prompt = PromptTemplate.from_template(
        "You are an expert ATS system and recruiter. Analyze the following resume text and score it out of 100 based on ATS readability, technical skills, leadership, achievements, and impact. Provide the response as JSON containing: ATS_score, Readability, Projects, Technical_Skills, Leadership, Achievements, Formatting, Impact, Grammar, Overall_score. \n\nResume Text:\n{text}"
    )
    
    chain = prompt | llm
    response = chain.invoke({"text": resume.parsed_text[:3000]}) # Limit to save tokens for parsing
    
    # Normally we would parse JSON, for now we just return the raw text generated by LLM
    return {"score_data": response.content}

@router.post("/match")
async def match_job(
    request: JobMatchRequest,
    db: Session = Depends(deps.get_db),
    current_user: User = Depends(deps.get_current_user),
):
    resume = db.query(Resume).filter(Resume.id == request.resume_id, Resume.owner_id == current_user.id).first()
    if not resume:
        raise HTTPException(status_code=404, detail="Resume not found")
        
    llm = ChatOpenAI(
        api_key=settings.OPENROUTER_API_KEY, 
        base_url="https://openrouter.ai/api/v1",
        model="nvidia/nemotron-3-ultra-550b-a55b:free"
    )
    prompt = PromptTemplate.from_template(
        "Compare the following job description with the provided resume text. Calculate Match %, Missing Skills, Strengths, Weaknesses, and Recommendations. Provide response in JSON format. \n\nJob Description:\n{job}\n\nResume:\n{resume}"
    )
    
    chain = prompt | llm
    response = chain.invoke({"job": request.job_description, "resume": resume.parsed_text[:3000]})
    
    return {"match_data": response.content}

class GenerationRequest(BaseModel):
    resume_id: int
    context: str

@router.post("/cover-letter")
async def generate_cover_letter(
    request: GenerationRequest,
    db: Session = Depends(deps.get_db),
    current_user: User = Depends(deps.get_current_user),
):
    resume = db.query(Resume).filter(Resume.id == request.resume_id, Resume.owner_id == current_user.id).first()
    if not resume:
        raise HTTPException(status_code=404, detail="Resume not found")
        
    llm = ChatOpenAI(
        api_key=settings.OPENROUTER_API_KEY, 
        base_url="https://openrouter.ai/api/v1",
        model="nvidia/nemotron-3-ultra-550b-a55b:free"
    )
    prompt = PromptTemplate.from_template(
        "You are an expert career coach. Based on the following resume, write a highly professional, tailored cover letter for this context/job: {context}. \n\nResume:\n{resume}"
    )
    
    chain = prompt | llm
    response = chain.invoke({"context": request.context, "resume": resume.parsed_text[:3000]})
    
    return {"cover_letter": response.content}

@router.post("/interview-prep")
async def generate_interview_prep(
    request: GenerationRequest,
    db: Session = Depends(deps.get_db),
    current_user: User = Depends(deps.get_current_user),
):
    resume = db.query(Resume).filter(Resume.id == request.resume_id, Resume.owner_id == current_user.id).first()
    if not resume:
        raise HTTPException(status_code=404, detail="Resume not found")
        
    llm = ChatOpenAI(
        api_key=settings.OPENROUTER_API_KEY, 
        base_url="https://openrouter.ai/api/v1",
        model="nvidia/nemotron-3-ultra-550b-a55b:free"
    )
    prompt = PromptTemplate.from_template(
        "You are an expert technical interviewer. Based on the following resume and this context/job: {context}, generate 5 highly tailored technical questions, 3 behavioral questions, and 2 system design questions the candidate is likely to face. Provide detailed answers/tips for how the candidate should answer them.\n\nResume:\n{resume}"
    )
    
    chain = prompt | llm
    response = chain.invoke({"context": request.context, "resume": resume.parsed_text[:3000]})
    
    return {"interview_prep": response.content}
